development: &development
  secret_key_base:   <%= ENV['DF_SECRET_KEY_BASE']   || '9e010ee2f52af762916406fd2ac488c5694a6cc784777136e657511f8bbc7a73f96d59c0a9a778a0d7cf6406f8ecbf77efe4701dfbd63d8248fc7cc7f32dea97' %>
  secret_key_attr:   <%= ENV['DF_SECRET_KEY_ATTR']   || 'e69fc5960ca0e8700844a3a25fe80373b41c0a265d342eba06950113f3766fd983bad9ec51bf36eb615d9711bfe1dd90b8e35f01841b323f604ffee857e32055' %>
  secret_key_devise: <%= ENV['DF_SECRET_KEY_DEVISE'] || 'f4e23c4388dc600e503a09ad057b8271d8fcf4c2cd6723b44f33db638e49075fe96bc545eed9110ded0c5df505625d4e1c838b718349eecf1d39270d0829d5b9' %>
  secret_key_aaf:    <%= ENV['DF_SECRET_KEY_AAF']    || 'secretsecret12345' %>
  secret_key_moss:   <%= ENV['DF_SECRET_KEY_MOSS'] %>
test:
  <<: *development
staging:
  <<: *development
production:
  secret_key_base:   <%= ENV['DF_SECRET_KEY_BASE']   %>
  secret_key_attr:   <%= ENV['DF_SECRET_KEY_ATTR']   %>
  secret_key_devise: <%= ENV['DF_SECRET_KEY_DEVISE'] %>
  secret_key_aaf:    <%= ENV['DF_SECRET_KEY_AAF']    %>
  secret_key_moss:   <%= ENV['DF_SECRET_KEY_MOSS']   %>
